x-app-common: &app-common
  build:
    context: .
    dockerfile: tools/docker/api/Dockerfile
  env_file: ./tools/env/dev.env
  volumes:
    - ./api:/app
    - ./tools/docker/api/entrypoint.sh:/entrypoint.sh

services:
  api:
    <<: *app-common
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    restart: unless-stopped

  cli:
    <<: *app-common
    command: echo "Starting cli container..."
